// run with `node scripts/create-tables.js` after setting DATABASE_URL
// this helper will create the products/images tables with proper identity keys
import { Client } from 'pg';

async function main() {
  const client = new Client({ connectionString: process.env.DATABASE_URL });
  await client.connect();

  const sql = `
create table if not exists public.products (
  id bigint generated by default as identity not null,
  name text null,
  category_id smallint null,
  img text null,
  origin text null,
  description text null,
  detail text null,
  contact_address text null,
  constraint products_pkey primary key (id)
);

create table if not exists public.images (
  product_id bigint not null,
  image_url text not null,
  img_id bigint generated by default as identity not null,
  constraint images_pkey primary key (img_id)
);
`;
  await client.query(sql);
  console.log('tables created/ensured');
  await client.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
